# Generated by Django 6.0.5 on 2026-05-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_contato_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
